FORMAT: 1A
HOST: https://as.production.imp.mobilitaetsdienste.de:8443/imp-endpoint

# IMP North. Implemented & Dredd testable
This is a test API which can be automatically tested with the Dredd Tool.

# Group Car Sharing
This is a group of all car sharing related rest resources

## List of Car Sharing Locations with Basic Info [/imp-endpoint/api/V1/Resources/CarSharing/All?lat={lat}&lng={lng}&radius={radius}] 

This collection contains list of available car sharing locations specified by the query parameters (both free-floating cars and/or car stations) 
with basic information and a URI to acquire more details.
In case of station-based cars, only the URI of the Car Sharing station is returned; in case of free-floating cars, the URI to the car itself.

response attribute | json data type | comments
--- | --- | ---
actions | Array | 
id | Number | 
description | String | License ID or approximate location
type | String | 
uri | URI | URI
location | Object | Standard WGS 84 for polar coordinates { "latitude":Number, "longitude":Number, "system": ENUM{"WGS_84","GK4","ETRS89",...}  }
provider | String | 
availability | Double | Availability in percentage
operator | String | 

### Getting all car sharing locations [GET]
@testable


+ Parameters
    + lat (string, `52.52`) ... String `lat` latitude value. Has example value.
    + lng (string, `13.39`) ... String `lng` longitude value. Has example value.
    + radius (string, `1000`) ... String `radius` longitude value. Has example value.
    

+ Response 200 (application/json)

        {
            "metaData": [
                {
                    "serviceAlias": "flinkster",
                    "lastUpdateTime": "2014-07-08T10:56:08+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "car2Go",
                    "lastUpdateTime": "2014-07-08T10:51:25+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "citeeCar",
                    "lastUpdateTime": "2014-07-08T10:56:11+0200",
                    "messages": []
                }
            ],
            "resources": [
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Stations/203870/Process?action=book"
                        }
                    ],
                    "id": 203870,
                    "description": "Caroline-Michaelis-Straße",
                    "type": "Stations",
                    "uri": "Resources/CarSharing/Stations/203870",
                    "location": {
                        "latitude": 52.533559809882156,
                        "longitude": 13.382519781589508,
                        "system": "WGS_84"
                    },
                    "provider": "flinkster",
                    "availability": 100,
                    "operator": "FlinksterDB"
                },
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Stations/203873/Process?action=book"
                        }
                    ],
                    "id": 203873,
                    "description": "Klosterstraße",
                    "type": "Stations",
                    "uri": "Resources/CarSharing/Stations/203873",
                    "location": {
                        "latitude": 52.517675064586484,
                        "longitude": 13.412365379013067,
                        "system": "WGS_84"
                    },
                    "provider": "flinkster",
                    "availability": 100,
                    "operator": "FlinksterDB"
                },
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Cars/203868/Process?action=book"
                        }
                    ],
                    "id": 203868,
                    "description": "B-GO4012",
                    "type": "Cars",
                    "uri": "Resources/CarSharing/Cars/203868",
                    "location": {
                        "latitude": 52.52244,
                        "longitude": 13.40559,
                        "system": "WGS_84"
                    },
                    "provider": "car2Go",
                    "availability": 100,
                    "operator": "Car2Go_Berlin"
                }
            ]
        }        


## List of free-floating Cars with Basic Info [/imp-endpoint/api/V1/Resources/CarSharing/Cars?lat={lat}&lng={lng}&radius={radius}&f_cars={fuelTypeJson}]

This collection contains a list of available free-floating cars in a specific area (NOTE: for free-floating car sharing only!).
The optional filter `f_cars` can be used to get cars with a specific `fuelType`
Request Headers: If-Modified-Since - [Optional] Request only resources modified after a particular date-time. Date time in HTTP date format for e.g. Wed, 09 Apr 2008 23:55:38 GMT (TODO)

response attribute | json data type | comments
--- | --- | ---
actions | Array | 
id | Number | car id
description | String | License ID or approximate location
type | String | "CarSharingCarDetails"
uri | URI | URI
location | Object | Standard WGS 84 for polar coordinates { "latitude":Number, "longitude":Number, "system": ENUM{"WGS_84","GK4","ETRS89",...}  }
provider | String | 
availability | Double | Svailability in percentage
operator | String | "Car2Go_Berlin" etc.
model | String | 
address | String | Street, city, etc.
licenseId | String | License ID
category | String | ENUM{"Fullsize", "Compact", "Smallsize", ... }
fuelType | String | electric vehicle ("ELECTRICITY") or petrol car ("PETROL")
fuelLevel | Double | Fuel level in percentage
imageLink | Link | link to the car image

### Getting free-floating Cars [GET] 
@testable

+ Parameters
    + lat (string, `52.52`) ... String `lat` latitude value. Has example value.
    + lng (string, `13.39`) ... String `lng` longitude value. Has example value.
    + radius (string, `3000`) ... String `radius` radius value. Has example value.
    + fuelTypeJson (optional, string, `{"fuelType":"ELECTRICITY"}`) ... String `fuelTypeJson` fuel type json data. Example value `{"fuelType":"ELECTRICITY"}` or `{"fuelType":"PETROL"}`
    
        
        
+ Response 200 (application/json)

        {
            "metaData": [
                {
                    "serviceAlias": "flinkster",
                    "lastUpdateTime": "2014-07-08T11:11:21+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "car2Go",
                    "lastUpdateTime": "2014-07-08T11:11:36+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "citeeCar",
                    "lastUpdateTime": "2014-07-08T10:56:11+0200",
                    "messages": []
                }
            ],
            "resources": [
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Cars/203868/Process?action=book"
                        }
                    ],
                    "id": 203868,
                    "description": "B-GO4012",
                    "type": "CarSharingCar",
                    "uri": "Resources/CarSharing/Cars/203868",
                    "location": {
                        "latitude": 52.52244,
                        "longitude": 13.40559,
                        "system": "WGS_84"
                    },
                    "provider": "car2Go",
                    "availability": 100,
                    "operator": "Car2Go_Berlin",
                    "model": "smart fortwo",
                    "address": null,
                    "licenseId": "B-GO4012",
                    "category": null,
                    "fuelType": "ELECTRICITY",
                    "fuelLevel": null,
                    "imageLink": null
                },
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Cars/203869/Process?action=book"
                        }
                    ],
                    "id": 203869,
                    "description": "B-GO4010",
                    "type": "CarSharingCar",
                    "uri": "Resources/CarSharing/Cars/203869",
                    "location": {
                        "latitude": 52.51613,
                        "longitude": 13.41643,
                        "system": "WGS_84"
                    },
                    "provider": "car2Go",
                    "availability": 100,
                    "operator": "Car2Go_Berlin",
                    "model": "smart fortwo",
                    "address": null,
                    "licenseId": "B-GO4010",
                    "category": null,
                    "fuelType": "ELECTRICITY",
                    "fuelLevel": null,
                    "imageLink": null
                }
            ]
        }
        
## List of Stations with Basic Info [/imp-endpoint/api/V1/Resources/CarSharing/Stations?lat={lat}&lng={lng}&radius={radius}&f_cars={fuelTypeJson}]

This collection contains a list of car sharing stations in a specific area (Note: for station-based car sharing) specified by the query parameters,
together with basic information and URI to acquire more details.
The optional filter `f_cars` can be used to get cars with a specific `fuelType`
Request Headers: If-Modified-Since - [Optional] Request only resources modified after a particular date-time. Date time in HTTP date format for e.g. Wed, 09 Apr 2008 23:55:38 GMT (TODO)

response attribute | json data type | comments
--- | --- | ---
metadata | Object | List of service providers and the last update times and failures if any [{serviceAlias:"XXX",lastUpdateTime:dd-mm-yyyyThhmmssZ,messages:[]}]
--- | --- | ---
resources | Array | Array of resources within the search area
--- | --- | ---
actions | Array | 
id | Number | 
description | String | Approximate location
type | String | 
uri | URI | URI to request more details
location | Object | Standard WGS 84 for polar coordinates { "latitude":Number, "longitude":Number, "system": ENUM{"WGS_84","GK4","ETRS89",...}  }
provider | String | 
availability | Double | Availability in percentage
operator | String | 
operatorURI | String | 
operatorName | String | 
address | Object | {"cityCode": String, "city": String, "street": String, "houseNo": String, "district": String, "region": String, "country": String}
modFlag | Enum | Type of modification to resource [New / Modified / Relocated / Deleted]. This attribute is present only when the If-Modified-Since header is passed in the request 


### Getting car sharing station list [GET] 
@testable

+ Parameters
    + lat (string, `52.52`) ... String `lat` latitude value. Has example value.
    + lng (string, `13.39`) ... String `lng` longitude value. Has example value.
    + radius (string, `3000`) ... String `radius` radius value. Has example value.
    + fuelTypeJson (optional, string, `{"fuelType":"ELECTRICITY"}`) ... String `fuelTypeJson` fuel type json data. Example value `{"fuelType":"ELECTRICITY"}` or `{"fuelType":"PETROL"}`
        
+ Response 200 (application/json)

        {
            "metaData": [
                {
                    "serviceAlias": "driveNow",
                    "lastUpdateTime": "2014-04-28T12:15:19+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "car2Go",
                    "lastUpdateTime": "2014-04-28T12:15:25+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "flinkster",
                    "lastUpdateTime": "2014-04-28T12:15:25+0200",
                    "messages": []
                }
            ],
            "resources": [
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Stations/55221/Process?action=book"
                        }
                    ],
                    "id": 55221,
                    "description": "Handwerkervereinshaus / Sophienstraße",
                    "type": "CarSharingStation",
                    "uri": "Resources/CarSharing/Stations/55221",
                    "location": {
                        "latitude": 52.52561167074207,
                        "longitude": 13.401126265525818,
                        "system": "WGS_84"
                    },
                    "provider": "FlinksterDB",
                    "availability" : 100,
                    "operator": "FlinksterDB",
                    "phoneNo": null,
                    "operatorURI": null,
                    "operatorName": "FlinksterDB",
                    "address": {
                        "citycode": "10178",
                        "city": "Berlin",
                        "street": "Sophienstraße",
                        "houseno": "18",
                        "district": "Mitte",
                        "region": null,
                        "country": null
                    }
                },
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Stations/55415/Process?action=book"
                        }
                    ],
                    "id": 55415,
                    "description": "Schumannstraße",
                    "type": "CarSharingStation",
                    "uri": "Resources/CarSharing/Stations/55415",
                    "location": {
                        "latitude": 52.523728447748866,
                        "longitude": 13.380703926086426,
                        "system": "WGS_84"
                    },
                    "provider": "FlinksterDB",
                    "availability" : 100,
                    "operator": "FlinksterDB",
                    "phoneNo": null,
                    "operatorURI": null,
                    "operatorName": "FlinksterDB",
                    "address": {
                        "citycode": "10117",
                        "city": "Berlin",
                        "street": "Schumannstraße",
                        "houseno": null,
                        "district": "Mitte",
                        "region": null,
                        "country": null
                    }
                }
            ]
        }  
        