FORMAT: 1A
HOST: https://as.production.imp.mobilitaetsdienste.de:8443/imp-endpoint

# IMP North. Implemented & Dredd testable
This is a test API which can be automatically tested with the Dredd Tool.

# Group Car Sharing
This is a group of all car sharing related rest resources

## List of Car Sharing Locations with Basic Info [/imp-endpoint/api/V1/Resources/CarSharing/All?lat={lat}&lng={lng}&radius={radius}] 

This collection contains list of available car sharing locations specified by the query parameters (both free-floating cars and/or car stations) 
with basic information and a URI to acquire more details.
In case of station-based cars, only the URI of the Car Sharing station is returned; in case of free-floating cars, the URI to the car itself.

The If-Modified-Since (optional) can be set to a specific date-time in order to request only resources modified after a particular date-time. Date time in HTTP date format for e.g. Wed, 09 Apr 2008 23:55:38 GMT

response attribute | json data type | comments
--- | --- | ---
metadata | Object | List of service providers and the last update times and failures if any [{serviceAlias:"XXX",lastUpdateTime:dd-mm-yyyyThhmmssZ,messages:[]}]
--- | --- | ---
resources | Array | Array of resources
--- | --- | ---
actions | Array | 
id | Number | 
description | String | License ID or approximate location
type | String | 
uri | URI | URI
location | Object | Standard WGS 84 for polar coordinates { "latitude":Number, "longitude":Number, "system": ENUM{"WGS_84","GK4","ETRS89",...}  }
provider | String | 
availability | Double | Availability in percentage
operator | String | 
modFlag | Enum | Type of modification to resource [New / Modified / Relocated / Deleted]. This attribute is present only when the If-Modified-Since header is passed in the request

### Getting all car sharing locations [GET]
@testable

+ Parameters
    + lat (string, `52.52`) ... String `lat` latitude value. Has example value.
    + lng (string, `13.39`) ... String `lng` longitude value. Has example value.
    + radius (string, `1000`) ... String `radius` longitude value. Has example value.

+ Request

    + Headers
        
            If-Modified-Since: Wed, 09 Apr 2008 23:55:38 GMT 

+ Response 200 (application/json)
    
    + Body
    
            {
            "metaData": [
                {
                    "serviceAlias": "driveNow",
                    "lastUpdateTime": "2014-07-09T12:36:24+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "car2Go",
                    "lastUpdateTime": "2014-07-09T12:36:38+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "flinkster",
                    "lastUpdateTime": "2014-07-09T12:36:46+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "citeeCar",
                    "lastUpdateTime": "2014-07-09T12:26:09+0200",
                    "messages": []
                }
            ],
            "resources": [
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Cars/235787/Process?action=book"
                        }
                    ],
                    "id": 235787,
                    "description": "Philbert",
                    "type": "Cars",
                    "uri": "Resources/CarSharing/Cars/235787",
                    "location": {
                        "latitude": 52.520018,
                        "longitude": 13.390876,
                        "system": "WGS_84"
                    },
                    "provider": "driveNow",
                    "availability": 100,
                    "operator": "DriveNow",
                    "modFlag": "Relocated"
                },
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Cars/235788/Process?action=book"
                        }
                    ],
                    "id": 235788,
                    "description": "Chico",
                    "type": "Cars",
                    "uri": "Resources/CarSharing/Cars/235788",
                    "location": {
                        "latitude": 52.513842,
                        "longitude": 13.385001,
                        "system": "WGS_84"
                    },
                    "provider": "driveNow",
                    "availability": 100,
                    "operator": "DriveNow",
                    "modFlag": "Deleted"
                }
                ]
            }        


## List of free-floating Cars with Basic Info [/imp-endpoint/api/V1/Resources/CarSharing/Cars?lat={lat}&lng={lng}&radius={radius}&f_cars={fuelTypeJson}]

This collection contains a list of available free-floating cars in a specific area (NOTE: for free-floating car sharing only!).
The optional filter `f_cars` can be used to get cars with a specific `fuelType`

The If-Modified-Since (optional) can be set to a specific date-time in order to request only resources modified after a particular date-time. Date time in HTTP date format for e.g. Wed, 09 Apr 2008 23:55:38 GMT

response attribute | json data type | comments
--- | --- | ---
metadata | Object | List of service providers and the last update times and failures if any [{serviceAlias:"XXX",lastUpdateTime:dd-mm-yyyyThhmmssZ,messages:[]}]
--- | --- | ---
resources | Array | Array of resources
--- | --- | ---
actions | Array | 
id | Number | car id
description | String | License ID or approximate location
type | String | "CarSharingCarDetails"
uri | URI | URI
location | Object | Standard WGS 84 for polar coordinates { "latitude":Number, "longitude":Number, "system": ENUM{"WGS_84","GK4","ETRS89",...}  }
provider | String | 
availability | Double | Svailability in percentage
operator | String | "Car2Go_Berlin" etc.
model | String | 
address | String | Street, city, etc.
licenseId | String | License ID
category | String | ENUM{"Fullsize", "Compact", "Smallsize", ... }
fuelType | String | electric vehicle ("ELECTRICITY") or petrol car ("PETROL")
fuelLevel | Double | Fuel level in percentage
imageLink | Link | link to the car image
modFlag | Enum | Type of modification to resource [New / Modified / Relocated / Deleted]. This attribute is present only when the If-Modified-Since header is passed in the request

### Getting free-floating Cars [GET] 
@testable

+ Parameters
    + lat (string, `52.52`) ... String `lat` latitude value. Has example value.
    + lng (string, `13.39`) ... String `lng` longitude value. Has example value.
    + radius (string, `3000`) ... String `radius` radius value. Has example value.
    + fuelTypeJson (optional, string, `{"fuelType":"ELECTRICITY"}`) ... String `fuelTypeJson` fuel type json data. Example value `{"fuelType":"ELECTRICITY"}` or `{"fuelType":"PETROL"}`

+ Request

    + Headers
    
            If-Modified-Since: Wed, 09 Apr 2008 23:55:38 GMT     
        
        
+ Response 200 (application/json)

    + Body
    
            {
            "metaData": [
                {
                    "serviceAlias": "driveNow",
                    "lastUpdateTime": "2014-07-09T12:36:24+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "car2Go",
                    "lastUpdateTime": "2014-07-09T12:41:23+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "flinkster",
                    "lastUpdateTime": "2014-07-09T12:41:25+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "citeeCar",
                    "lastUpdateTime": "2014-07-09T12:26:09+0200",
                    "messages": []
                }
            ],
            "resources": [
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Cars/235787/Process?action=book"
                        }
                    ],
                    "id": 235787,
                    "description": "Philbert",
                    "type": "CarSharingCar",
                    "uri": "Resources/CarSharing/Cars/235787",
                    "location": {
                        "latitude": 52.520018,
                        "longitude": 13.390876,
                        "system": "WGS_84"
                    },
                    "provider": "driveNow",
                    "availability": 100,
                    "operator": "DriveNow",
                    "modFlag": "Relocated",
                    "model": "MINI Cabrio",
                    "address": null,
                    "licenseId": "M-DX7999",
                    "category": null,
                    "fuelType": "PETROL",
                    "fuelLevel": null,
                    "imageLink": null
                },
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Cars/235788/Process?action=book"
                        }
                    ],
                    "id": 235788,
                    "description": "Chico",
                    "type": "CarSharingCar",
                    "uri": "Resources/CarSharing/Cars/235788",
                    "location": {
                        "latitude": 52.513842,
                        "longitude": 13.385001,
                        "system": "WGS_84"
                    },
                    "provider": "driveNow",
                    "availability": 100,
                    "operator": "DriveNow",
                    "modFlag": "Deleted",
                    "model": "BMW X1",
                    "address": null,
                    "licenseId": "M-DX7124",
                    "category": null,
                    "fuelType": "DIESEL",
                    "fuelLevel": null,
                    "imageLink": null
                }
                ]
            }
        
## List of Stations with Basic Info [/imp-endpoint/api/V1/Resources/CarSharing/Stations?lat={lat}&lng={lng}&radius={radius}&f_cars={fuelTypeJson}&operatorId={operatorId}]

This collection contains a list of car sharing stations in a specific area (Note: for station-based car sharing) specified by the query parameters,
together with basic information and URI to acquire more details.
The optional filter `f_cars` can be used to get cars with a specific `fuelType`

The If-Modified-Since (optional) can be set to a specific date-time in order to request only resources modified after a particular date-time. Date time in HTTP date format for e.g. Wed, 09 Apr 2008 23:55:38 GMT

response attribute | json data type | comments
--- | --- | ---
metadata | Object | List of service providers and the last update times and failures if any [{serviceAlias:"XXX",lastUpdateTime:dd-mm-yyyyThhmmssZ,messages:[]}]
--- | --- | ---
resources | Array | Array of resources within the search area
--- | --- | ---
actions | Array | 
id | Number | 
description | String | Approximate location
type | String | 
uri | URI | URI to request more details
location | Object | Standard WGS 84 for polar coordinates { "latitude":Number, "longitude":Number, "system": ENUM{"WGS_84","GK4","ETRS89",...}  }
provider | String | 
availability | Double | Availability in percentage
operator | String | 
operatorURI | String | 
operatorName | String | 
address | Object | {"cityCode": String, "city": String, "street": String, "houseNo": String, "district": String, "region": String, "country": String}
modFlag | Enum | Type of modification to resource [New / Modified / Relocated / Deleted]. This attribute is present only when the If-Modified-Since header is passed in the request 


### Getting car sharing station list [GET] 
@testable

+ Parameters
    + lat (string, `52.52`) ... String `lat` latitude value. Has example value.
    + lng (string, `13.39`) ... String `lng` longitude value. Has example value.
    + radius (string, `3000`) ... String `radius` radius value. Has example value.
    + fuelTypeJson (optional, string, `{"fuelType":"ELECTRICITY"}`) ... String `fuelTypeJson` fuel type json data. Example value `{"fuelType":"ELECTRICITY"}` or `{"fuelType":"PETROL"}`
    + operatorId (optional, string, `FlinksterDB`) ... String `operatorId` operator id data. Has example value.

+ Request

    + Headers
    
            If-Modified-Since: Wed, 09 Apr 2008 23:55:38 GMT 
        
+ Response 200 (application/json)
            
    + Body
    
            {
            "metaData": [
                {
                    "serviceAlias": "driveNow",
                    "lastUpdateTime": "2014-07-09T12:56:21+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "car2Go",
                    "lastUpdateTime": "2014-07-09T13:01:24+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "flinkster",
                    "lastUpdateTime": "2014-07-09T12:41:25+0200",
                    "messages": []
                },
                {
                    "serviceAlias": "citeeCar",
                    "lastUpdateTime": "2014-07-09T12:26:09+0200",
                    "messages": []
                }
            ],
            "resources": [
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Stations/236082/Process?action=book"
                        }
                    ],
                    "id": 236082,
                    "description": "Handwerkervereinshaus / Sophienstraße",
                    "type": "CarSharingStation",
                    "uri": "Resources/CarSharing/Stations/236082",
                    "location": {
                        "latitude": 52.52561167074207,
                        "longitude": 13.401126265525818,
                        "system": "WGS_84"
                    },
                    "provider": "flinkster",
                    "availability": 100,
                    "operator": "FlinksterDB",
                    "modFlag": "Modified",
                    "phoneNo": null,
                    "operatorURI": null,
                    "operatorName": "FlinksterDB",
                    "address": {
                        "citycode": "10178",
                        "city": "Berlin",
                        "street": "Sophienstraße",
                        "houseno": "18",
                        "district": "Mitte",
                        "region": null,
                        "country": null
                    }
                },
                {
                    "actions": [
                        {
                            "name": "book",
                            "method": "POST",
                            "uri": "Resources/CarSharing/Stations/236084/Process?action=book"
                        }
                    ],
                    "id": 236084,
                    "description": "Caroline-Michaelis-Straße",
                    "type": "CarSharingStation",
                    "uri": "Resources/CarSharing/Stations/236084",
                    "location": {
                        "latitude": 52.533559809882156,
                        "longitude": 13.382519781589508,
                        "system": "WGS_84"
                    },
                    "provider": "flinkster",
                    "availability": 100,
                    "operator": "FlinksterDB",
                    "modFlag": "Modified",
                    "phoneNo": null,
                    "operatorURI": null,
                    "operatorName": "FlinksterDB",
                    "address": {
                        "citycode": "10115",
                        "city": "Berlin",
                        "street": "Caroline-Michaelis-Straße",
                        "houseno": "5-11",
                        "district": "Mitte",
                        "region": null,
                        "country": null
                    }
                }
                ]
            }  
        
# Group EV Charging Station
This is a group of all EV Charging related rest resources    
    
## List of EV Charging Stations with Basic Info [/imp-endpoint/api/V1/Resources/EVCharging/Stations?lat={lat}&lng={lng}&radius={radius}]
This collection contains a list of all electric vehicle (EV) charging stations specified by query parameters (and body), 
together with geo location, name, and a URI to acquire more details.

The If-Modified-Since (optional) can be set to a specific date-time in order to request only resources modified after a particular date-time.
Date time in HTTP date format for e.g. Wed, 09 Apr 2008 23:55:38 GMT

response attribute | json data type | comments
--- | --- | ---
metadata | Object | List of service providers and the last update times and failures if any [{serviceAlias:"XXX",lastUpdateTime:dd-mm-yyyyThhmmssZ,messages:[]}]
--- | --- | ---
resources | Array | Array of resources within the search area
--- | --- | ---
actions | Array | List of available actions on this resource
id | Number | Internal charging station identification numberg
description | String | Approximate location or parking garage operator
type | String | ="EVChargingStation" 
uri | URI | URI to request more details
location | Object | Standard WGS 84 for polar coordinates { "latitude":Number, "longitude":Number, "system": ENUM{"WGS_84","GK4","ETRS89",...}  }
provider |  String| Charging station operator (usually equals provider)
availability | Double | Availability in percentage
operator | String | Charging station provider (usually equals operator)
address | Object | 
plugTypes | Enum value | Type of the plug.
power | Number |  
modFlag | Enum | Type of modification to resource [New / Modified / Relocated / Deleted]. This attribute is present only when the If-Modified-Since header is passed in the request  

### Getting EV charging stations [GET]
@testable

+ Parameters
    + lat (string, `52.52`) ... String `lat` latitude value. Has example value.
    + lng (string, `13.39`) ... String `lng` longitude value. Has example value.
    + radius (string, `1000`) ... String `radius` longitude value. Has example value.
    
+ Request

    + Headers
    
            If-Modified-Since: Wed, 09 Apr 2008 23:55:38 GMT 
        
+ Response 200 (application/json)
    
    + Body  
    
            {
                "metaData": [
                    {
                        "serviceAlias": "vattenfall",
                        "lastUpdateTime": "2014-07-09T14:06:39+0200",
                        "messages": []
                    },
                    {
                        "serviceAlias": "hubject",
                        "lastUpdateTime": "2014-07-09T13:07:07+0200",
                        "messages": []
                    }
                ],
                "resources": [
                    {
                        "actions": [],
                        "id": 238909,
                        "description": "Conti",
                        "type": "EVChargingStation",
                        "uri": "Resources/EVCharging/Stations/238909",
                        "location": {
                            "latitude": 52.51474,
                            "longitude": 13.38639,
                            "system": "WGS_84"
                        },
                        "provider": "vattenfall",
                        "availability": 0,
                        "operator": "Vattenfall",
                        "modFlag": "Relocated",
                        "address": {
                            "citycode": "10117",
                            "city": "Berlin",
                            "street": "Glinkastr.",
                            "houseno": "38",
                            "district": null,
                            "region": null,
                            "country": null
                        },
                        "plugTypes": [
                            "Type2Outlet",
                            "TypeFSchuko"
                        ],
                        "power": {
                            "unit": "KiloWatt",
                            "value": 11040
                        }
                    }
                ]
            }
  
        
  
# Group Traffic Info Level-of-Service. WMS
This is a group of all traffic info (WMS) related rest resources

## WMS PNG file for road traffic (Level of Service). [/imp-endpoint/api/V1/Info/TrafficInfo]

width. `width={w}`: width of map output in pixels (semantics according to WMS GetMap request). The default value is width=250
height `height={h}`: height of map output in pixels (semantics according to WMS GetMap request). The default value is height=250
  
Behavior: additional parameters have to be passed to WMS server such as format=image/png.

Response is a PNG content which dispays the current traffic situation. Please note: The accept-header of this request must be set to "image/png".

### Getting a specific charging station [GET] 
@testable

+ Request

    + Headers
            accept: image/png
    
        
+ Response 200 (application/json)

    +Headers
            Content-Type: image/png
                
    + Body

        {  
            "... this should be a PNG ..."
        } 

    